server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**

      discovery:
        locator:
          enabled: true
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
