server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE  
          predicates:
            - Path=/api/companies/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
