server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-service
          uri: http://localhost:8882
          predicates:
            - Path=/api/companies/**
        - id: user-service
          uri: http://localhost:8881
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.config: DEBUG
