server:
  port: 8882

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  application:
    name: company-service

user:
  service:
    url: http://user-service:8881
