server:
  port: 8882

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
  application:
    name: company-service

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true

user:
  service:
    url: http://user-service:8881
