server:
  port: 8882

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/5dhub
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
  application:
    name: company-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true

user:
  service:
    url: http://localhost:8881
