server:
  port: 8882

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: postgres  
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  application:
    name: company-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

user:
  service:
    url: http://localhost:8881
