server:
  port: 8881

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  client:
    config:
      company-service:
        connect-timeout: 5000
        read-timeout: 5000
        retryer:
          period: 1000
          max-period: 2000
          max-attempts: 3
      default:
        logger-level: basic

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
